### ISSUE TITLE
Missing rationale for closed source

### ISSUE THREAD

**Issue by sweir27** [artsy/convection#22]
This repo is closed source but seems to be missing rationale in the README. If this repo should remain closed, you can pass this test with something like this:

Rationale for Closed Source: This repo is closed source because <insert rationale here>.

Danger-Issue-ID-convection

**Comment by jonallured** [comment]
Ok I didn't do that last bit yet about making a blog post but I did switch the repo to open so going to close this one and come back to that later.

**Comment by damassi** [comment]
Lets do the blog post once we're a little further along, right now its a pretty vanilla rails app.

**Comment by ashfurrow** [comment]
So exciting to see the Consignments team kick things off with such a cool move. Thanks for living up to our principles, y'all!
